# Generated from labels.tmp for the BET single-area model.
# Historical area suffixes in display labels are retained; MFCL region is 1 for every fishery.

fishery_map <- data.frame(
  fishery_name = c(
    "LL.WEST.1",
    "LL.EAST.1",
    "LL.US.1",
    "LL.ALL.2",
    "LL.OS.2",
    "LL.ARCH.3",
    "LL.WEST.3",
    "LL.EAST.4",
    "LL.OS.3",
    "LL.ALL.5",
    "LL.AU.5",
    "PS.JP.1",
    "PL.JP.1",
    "HL.ID.2",
    "HL.PH.2",
    "PL.ALL.2",
    "PS.ID.2",
    "PS.PH.2",
    "PS.ASS.2",
    "PS.UNA.2",
    "MISC.ID.2",
    "MISC.PH.2",
    "MISC.VN.2",
    "PL.ALL.WEST.3",
    "PS.ASS.WEST.3",
    "PS.ASS.EAST.4",
    "PS.UNA.WEST.3",
    "PS.UNA.EAST.4",
    "Index 1"
  ),
  fishery = 1:29,
  region = rep(1L, 29),
  group = c(
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "LL",
    "PS",
    "PL",
    "HL",
    "HL",
    "PL",
    "PS",
    "PS",
    "PS",
    "PS",
    "MISC",
    "MISC",
    "MISC",
    "PL",
    "PS",
    "PS",
    "PS",
    "PS",
    "Index"
  ),
  stringsAsFactors = FALSE
)

